theme: null
domain: couleslaw.github.io
baseurl: /
url: https://couleslaw.github.io
github_username: couleslaw
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
include: [".htaccess"]
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
