theme: null
domain: couleslaw.github.io
baseurl: ""
url: https://couleslaw.github.io
github_username: couleslaw
favicon: /favicon.ico
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
